version: '3.8'

services:
  app:
    image: jooeonlee/graydang:latest
    container_name: graydang-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DATASOURCE_URL_PROD}
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME_PROD}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD_PROD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      BILL_API_KEY: ${BILL_API_KEY}
      BILL_API_KEY_V2: ${BILL_API_KEY_V2}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      BASE_URL: ${BASE_URL}
      AWS_S3_ACCESS_KEY: ${AWS_S3_ACCESS_KEY}
      AWS_S3_SECRET_KEY: ${AWS_S3_SECRET_KEY}
      DEFAULT_PROFILE_IMAGE_URL: ${DEFAULT_PROFILE_IMAGE_URL}
      JWT_SECRET: ${JWT_SECRET}
      ACCESS_TOKEN_EXPIRED_IN: ${ACCESS_TOKEN_EXPIRED_IN}
      REFRESH_TOKEN_EXPIRED_IN: ${REFRESH_TOKEN_EXPIRED_IN}
      SPRING_REDIS_HOST: ${SPRING_REDIS_HOST}
      SPRING_REDIS_PORT: ${SPRING_REDIS_PORT}
    restart: always

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: always
volumes:
  db-data:
