version: '3.8'

services:
  app:
    image: jooeonlee/graydang:latest
    container_name: graydang-app
    ports:
      - "8080:8080"
#    depends_on:
#      db:
#        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: ${DATASOURCE_URL_PROD}
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME_PROD}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD_PROD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      BILL_API_KEY: ${BILL_API_KEY}
      BILL_API_KEY_V2: ${BILL_API_KEY_V2}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      BASE_URL: ${BASE_URL}
    restart: always

volumes:
  db-data:
