version: '3.8'

services:
  app:
    image: jooeonlee/graydang:latest
    container_name: graydang-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: ${DATASOURCE_URL_PROD}
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME_PROD}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD_PROD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      BILL_API_KEY: ${BILL_API_KEY}
      BILL_API_KEY_V2: ${BILL_API_KEY_V2}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    restart: always

volumes:
  db-data:
