version: '3.8'

services:
  app:
    image: jooeonlee/graydang:latest
    container_name: graydang-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DATASOURCE_URL_PROD}
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME_PROD}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD_PROD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8
    container_name: graydang-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: graydang
      MYSQL_USER: user
      MYSQL_PASSWORD: pass1234
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: always

volumes:
  db-data:
