openapi:
  bill:
    service-key: dummy-bill-api-key
    service-key-v2: dummy-bill-api-key-v2

openai:
  api:
    key: dummy-openai-api-key
    model: gpt-4o-mini
    url: https://api.openai.com/v1/chat/completions

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  batch:
    jdbc:
      initialize-schema: always
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:dummy-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:dummy-google-client-secret}
            scope:
              - email
              - profile
          naver:
            client-id: ${NAVER_CLIENT_ID:dummy-naver-client-id}
            client-secret: ${NAVER_CLIENT_SECRET:dummy-naver-client-secret}
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

jwt:
  secret: ${JWT_SECRET:mySecretKeyForJWTForTestEnvironment}
  access-token-validity: 3600000 # 1 hour
  refresh-token-validity: 604800000 # 7 days
