server:
  forward-headers-strategy: framework

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL_PROD}
    username: ${DATASOURCE_USERNAME_PROD}
    password: ${DATASOURCE_PASSWORD_PROD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}

  batch:
    jdbc:
      initialize-schema: always

logging:
  custom:
    enabled: true
    http-request: false