server:
  forward-headers-strategy: framework

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL_PROD}
    username: ${DATASOURCE_USERNAME_PROD}
    password: ${DATASOURCE_PASSWORD_PROD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}

  batch:
    jdbc:
      initialize-schema: always

  kafka:
    # 9092 포트는 고정(내부 통신 표준)이지만, IP는 주입받습니다.
    # 만약 KAFKA_HOST 값이 없으면 에러가 나도록 설정합니다.
    bootstrap-servers: ${KAFKA_HOST}:9092

logging:
  custom:
    enabled: true
    http-request: false

app:
  topic:
    bill-notification: bill-notification-prod