openapi:
  bill:
    service-key: ${BILL_API_KEY}
    service-key-v2: ${BILL_API_KEY_V2}

spring:
  batch:
    jdbc:
      initialize-schema: never
    job:
      #name: billVoteResultJob
      enabled: false
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  # 운영 시에는 보통 validate 또는 none 사용
    properties:
      hibernate:
        format_sql: true